Repository ucsb-cs156-s25/proj-courses-s25-02, pull requests merged in 2025-05, with the labels that each got.

#23 mc - add placeholder page for GE search
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/GeneralEducation/Search/GeneralEducationSearchPage.js
  frontend/src/tests/pages/CourseDescriptions/GeneralEducation/Search/GeneralEducationSearchPage.test.js
Labels: 5

#21 ec - modified API endpoints to get classrooms for a building
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeBuildingController.java
  src/main/resources/application-production.properties
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeBuildingControllerTests.java
Labels: 10

#22 added api endpoint that returns the list of GE areas
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumControllerTests.java
Labels: 10, Merge Candidate-CI

#25 sw - Implement a Weekly View of Personal Schedules
  frontend/src/App.js
  frontend/src/index.css
  frontend/src/main/components/PersonalSchedules/PersonalScheduleEvent.js
  frontend/src/main/components/PersonalSchedules/PersonalSchedulePanel.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesDetailsPage.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesWeeklyViewPage.js
  frontend/src/main/utils/dateUtils.js
  frontend/src/stories/components/PersonalSchedules/PersonalScheduleEvent.stories.js
  frontend/src/stories/components/PersonalSchedules/PersonalSchedulePanel.stories.js
  frontend/src/stories/pages/PersonalSchedules/PersonalSchedulesDetailsPage.stories.js
  frontend/src/stories/pages/PersonalSchedules/PersonalSchedulesWeeklyViewPage.stories.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleEvent.test.js
  frontend/src/tests/components/PersonalSchedules/PersonalSchedulePanel.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesDetailsPage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesWeeklyViewPage.test.js
  frontend/src/tests/utils/dateUtils.test.js
Labels: 20, Merge Candidate-Dokku, FIXME-Deploy

#30 sw - UX IMPROVEMENT: Make width of pagination component consistent.
  frontend/src/main/components/Utils/OurPagination.js
  frontend/src/tests/components/Utils/OurPagination.test.js
Labels: 10

#24 Add drop down menu ge areas
  frontend/src/fixtures/singleAreaDropdownFixtures.js
  frontend/src/main/components/GEAreas/SingleAreaDropdown.js
  frontend/src/stories/components/GEAreas/SingleAreaDropdown.stories.js
  frontend/src/tests/components/GEAreas/SingleAreaDropdown.test.js
Labels: 10, Merge Candidate-CI

#27 jr - killed all modal logic mutations in SectionsTable.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: 10, Merge Candidate-CI

#26 ec - Fetched list of classrooms based on building in frontend
  frontend/src/App.js
  frontend/src/main/components/BasicCourseSearch/CourseOverTimeBuildingsSearchForm.js
  frontend/src/main/components/Jobs/UpdateCoursesByQuarterJobForm.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Quarters/SingleQuarterDropdown.js
  frontend/src/main/pages/CourseOverTime/CourseOverTimeBuildingsIndexPage.js
  frontend/src/stories/components/BasicCourseSearch/CourseOverTimeBuildingsSearchForm.stories.js
  frontend/src/stories/pages/CourseOverTime/CourseOverTimeBuildingsIndexPage.stories.js
  frontend/src/tests/components/BasicCourseSearch/CourseOverTimeBuildingsSearchForm.test.js
  frontend/src/tests/components/Jobs/UpdateCoursesByQuarterJobForm.test.js
  frontend/src/tests/components/Quarters/SingleQuarterDropdown.test.js
  frontend/src/tests/pages/CourseOverTime/CourseOverTimeBuildingsIndexPage.test.js
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeBuildingController.java
  src/main/resources/application-production.properties
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeBuildingControllerTests.java
Labels: 10, Merge Candidate-CI

#29 mc - Add an API Endpoint to Retrieve the List of GE Areas
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/courses/documents/GERequirement.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: 10, Merge Candidate-CI

#28 Xz-Paginate the Job Log Endpoint
  src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/courses/repositories/JobsRepository.java
  src/test/java/edu/ucsb/cs156/courses/controllers/JobsControllerTests.java
Labels: 10, Merge Candidate-CI
